# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Project SDK levels shared by all modules
minSdkVersion=26
targetSdkVersion=35
compileSdkVersion=35
ndkVersion=27.2.12479018
